[package]
name = "btc_memopool_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
serde_json = "1.0.128"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
rodio = "0.19.0"
chrono = "0.4.38"
